// <auto-generated />
using System;
using EduCenterOS.Modules.IdentityAccess.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduCenterOS.Modules.IdentityAccess.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityAccessDbContext))]
    [Migration("20261004164019_AuthenticationSessions")]
    partial class AuthenticationSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity_access")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduCenterOS.Modules.IdentityAccess.Domain.LoginTarget", b =>
                {
                    b.Property<byte[]>("Digest")
                        .HasColumnType("bytea")
                        .HasColumnName("digest");

                    b.PrimitiveCollection<DateTimeOffset[]>("AttemptsUtc")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]")
                        .HasColumnName("attempts_utc");

                    b.Property<DateTimeOffset>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.HasKey("Digest");

                    b.HasIndex("LastAttemptAtUtc");

                    b.ToTable("login_targets", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_login_target_budget", "octet_length(digest) = 32 AND cardinality(attempts_utc) <= 20");
                        });
                });

            modelBuilder.Entity("EduCenterOS.Modules.IdentityAccess.Domain.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("HashKeyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hash_key_version");

                    b.Property<string>("NormalizedTarget")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("normalized_target");

                    b.Property<DateTimeOffset?>("ProofExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proof_expires_at_utc");

                    b.Property<byte[]>("ProofHash")
                        .HasColumnType("bytea")
                        .HasColumnName("proof_hash");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Purpose", "NormalizedTarget")
                        .IsUnique()
                        .HasFilter("status IN (0,1)");

                    b.ToTable("otp_challenges", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_challenge_binding", "normalized_target ~ '^[+]201[0125][0-9]{8}$' AND octet_length(code_hash) = 32 AND length(hash_key_version) BETWEEN 1 AND 32");

                            t.HasCheckConstraint("ck_challenge_state", "status IN (0,1,2,3,4) AND failed_attempts BETWEEN 0 AND 10 AND purpose = 'RegisterAccount'");

                            t.HasCheckConstraint("ck_challenge_times", "expires_at_utc > created_at_utc AND (status <> 1 OR (proof_hash IS NOT NULL AND octet_length(proof_hash) = 32 AND verified_at_utc IS NOT NULL AND proof_expires_at_utc IS NOT NULL AND proof_expires_at_utc > verified_at_utc)) AND (status <> 0 OR proof_hash IS NULL)");
                        });
                });

            modelBuilder.Entity("EduCenterOS.Modules.IdentityAccess.Domain.PersonIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.HasKey("Id");

                    b.ToTable("person_identities", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_person_name", "(length(full_name) + length(regexp_replace(full_name, U&'[^\\+010000-\\+10FFFF]', '', 'g'))) BETWEEN 2 AND 200");
                        });
                });

            modelBuilder.Entity("EduCenterOS.Modules.IdentityAccess.Domain.RefreshTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_session_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ReplacedByTokenId")
                        .IsUnique()
                        .HasFilter("replaced_by_token_id IS NOT NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserSessionId", "ReplacedByTokenId");

                    b.ToTable("refresh_token_records", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_refresh_consumption", "(consumed_at_utc IS NULL AND replaced_by_token_id IS NULL) OR (consumed_at_utc IS NOT NULL AND replaced_by_token_id IS NOT NULL AND replaced_by_token_id <> id)");

                            t.HasCheckConstraint("ck_refresh_security", "octet_length(token_hash) = 32 AND version >= 1");

                            t.HasCheckConstraint("ck_refresh_times", "expires_at_utc > created_at_utc AND (consumed_at_utc IS NULL OR consumed_at_utc >= created_at_utc) AND (revoked_at_utc IS NULL OR revoked_at_utc >= created_at_utc)");
                        });
                });

            modelBuilder.Entity("EduCenterOS.Modules.IdentityAccess.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_address");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at_utc");

                    b.Property<string>("InitialOnboardingIntent")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("initial_onboarding_intent");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_utc");

                    b.Property<string>("NormalizedEmailAddress")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email_address");

                    b.Property<string>("NormalizedPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("normalized_phone_number");

                    b.Property<DateTimeOffset>("PasswordChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("PersonIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_identity_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("PhoneVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_verified_at_utc");

                    b.Property<long>("SecurityVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("security_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmailAddress")
                        .IsUnique()
                        .HasFilter("normalized_email_address IS NOT NULL");

                    b.HasIndex("NormalizedPhoneNumber")
                        .IsUnique();

                    b.HasIndex("PersonIdentityId")
                        .IsUnique();

                    b.ToTable("user_accounts", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_account_email", "email_address IS NOT DISTINCT FROM normalized_email_address AND (normalized_email_address IS NULL OR normalized_email_address = lower(normalized_email_address))");

                            t.HasCheckConstraint("ck_account_phone", "normalized_phone_number ~ '^[+]201[0125][0-9]{8}$' AND phone_number = normalized_phone_number");

                            t.HasCheckConstraint("ck_account_security", "status IN (0,1,2) AND security_version >= 1 AND version >= 1 AND access_failed_count >= 0");

                            t.HasCheckConstraint("ck_account_times", "phone_verified_at_utc <= created_at_utc AND password_changed_at_utc >= created_at_utc");
                        });
                });

            modelBuilder.Entity("EduCenterOS.Modules.IdentityAccess.Domain.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at_utc");

                    b.Property<string>("AssuranceLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("assurance_level");

                    b.Property<DateTimeOffset>("AuthenticatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authenticated_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("IdleExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_expires_at_utc");

                    b.Property<DateTimeOffset>("LastPrimaryAuthenticatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_primary_authenticated_at_utc");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<long>("SecurityVersionAtAuthentication")
                        .HasColumnType("bigint")
                        .HasColumnName("security_version_at_authentication");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "CreatedAtUtc", "Id");

                    b.ToTable("user_sessions", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_session_revocation", "(revoked_at_utc IS NULL AND revocation_reason IS NULL) OR (revoked_at_utc IS NOT NULL AND revocation_reason IS NOT NULL AND revoked_at_utc >= created_at_utc AND revocation_reason IN ('LogoutCurrent','LogoutAll','UserRequest','RefreshReuse','SecurityReset'))");

                            t.HasCheckConstraint("ck_session_security", "security_version_at_authentication >= 1 AND version >= 1 AND assurance_level = 'PrimaryAuthenticated'");

                            t.HasCheckConstraint("ck_session_times", "created_at_utc <= authenticated_at_utc AND authenticated_at_utc <= last_primary_authenticated_at_utc AND last_seen_at_utc >= created_at_utc AND idle_expires_at_utc > created_at_utc AND idle_expires_at_utc <= absolute_expires_at_utc");
                        });
                });

            modelBuilder.Entity("EduCenterOS.Modules.IdentityAccess.Domain.VerificationTarget", b =>
                {
                    b.Property<byte[]>("Digest")
                        .HasColumnType("bytea")
                        .HasColumnName("digest");

                    b.PrimitiveCollection<DateTimeOffset[]>("IssuesUtc")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]")
                        .HasColumnName("issues_utc");

                    b.Property<DateTimeOffset?>("LastIssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_issued_at_utc");

                    b.PrimitiveCollection<DateTimeOffset[]>("VerificationsUtc")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]")
                        .HasColumnName("verifications_utc");

                    b.HasKey("Digest");

                    b.HasIndex("LastIssuedAtUtc");

                    b.ToTable("verification_targets", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_target_budget", "octet_length(digest) = 32 AND cardinality(issues_utc) <= 3 AND cardinality(verifications_utc) <= 10");
                        });
                });

            modelBuilder.Entity("EduCenterOS.Modules.IdentityAccess.Infrastructure.Persistence.RateKeyBinding", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<byte[]>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("fingerprint");

                    b.HasKey("Id");

                    b.ToTable("rate_key_binding", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_rate_key_binding", "id = 1 AND octet_length(fingerprint) = 32");
                        });
                });

            modelBuilder.Entity("EduCenterOS.Modules.IdentityAccess.Domain.RefreshTokenRecord", b =>
                {
                    b.HasOne("EduCenterOS.Modules.IdentityAccess.Domain.UserSession", null)
                        .WithMany()
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduCenterOS.Modules.IdentityAccess.Domain.RefreshTokenRecord", null)
                        .WithMany()
                        .HasForeignKey("UserSessionId", "ReplacedByTokenId")
                        .HasPrincipalKey("UserSessionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EduCenterOS.Modules.IdentityAccess.Domain.UserAccount", b =>
                {
                    b.HasOne("EduCenterOS.Modules.IdentityAccess.Domain.PersonIdentity", null)
                        .WithOne()
                        .HasForeignKey("EduCenterOS.Modules.IdentityAccess.Domain.UserAccount", "PersonIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EduCenterOS.Modules.IdentityAccess.Domain.UserSession", b =>
                {
                    b.HasOne("EduCenterOS.Modules.IdentityAccess.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
